export interface EducationGuide { lead: string; sections: Array<{ title: string; explanation: string; example: string; bullets: string[] }>; questions: Array<{ question: string; answer: string }>; }

const GENERIC: EducationGuide = { lead: 'Bu derste kavramın ne olduğunu, hangi veriden üretildiğini, hangi koşullarda işe yaradığını ve hangi durumda yanıltıcı olabileceğini örneklerle öğreneceksin.', sections: [{ title: 'Kavramı doğru yere koy', explanation: 'Bir gösterge veya piyasa kavramı hiçbir zaman tek başına alım-satım emri değildir. Önce zaman ufku, trend, likidite ve haber bağlamı belirlenir; sonra ölçüm karar planına çevrilir.', example: 'Aynı sinyal yükselen trendde devam, yatay piyasada ise yanlış kırılım uyarısı olabilir.', bullets: ['Tanım ve ölçüm', 'Kullanım koşulları', 'Geçersizlik koşulu'] }, { title: 'Uygulamalı okuma', explanation: 'Önce geçmişte ne olduğunu ölç, sonra bugün aynı koşulların bulunup bulunmadığını kontrol et. Geçmiş örnek geleceğin garantisi değil, hipotezi sınamak için örneklemdir.', example: '30 geçmiş sinyali win rate, ortalama kazanç, ortalama kayıp ve maksimum düşüş ile ayrı ayrı kaydet.', bullets: ['Veriyi doğrula', 'Senaryoyu yaz', 'Riski hesapla'] }], questions: [{ question: 'Bu konu neyi ölçüyor?', answer: 'Fiyat, hacim, şirket veya yatırımcı davranışının hangi yönünü ölçtüğünü söyleyemiyorsan sinyali karar olarak kullanma.' }, { question: 'Ne zaman çalışmaz?', answer: 'Haber şoku, düşük likidite, veri hatası ve farklı piyasa rejimleri yöntemin geçmişteki davranışını bozabilir.' }] };

const GUIDES: Record<string, EducationGuide> = {
    'mum-ve-fiyat-aksiyonu': { lead: 'Mum, belirli bir zaman aralığındaki açılış, en yüksek, en düşük ve kapanış fiyatını tek bir görselde toplar. Fiyat aksiyonu ise bu mumları tek tek isimlendirmekten çok alıcı ve satıcının nerede güçlendiğini okumaktır.', sections: [{ title: 'Mumun dört parçası', explanation: 'Gövde açılış-kapanış farkını, üst ve alt fitiller o aralıkta reddedilen fiyatları gösterir. Kapanışın mum aralığındaki yeri önemlidir: yüksekten kapanış alıcının, düşükten kapanış satıcının seans sonuna kadar baskın kaldığını anlatır.', example: '100 TL açılıp 105 TL kapanan, 107 TL görüp 99 TL’ye inen mumda üst fitil alıcıların yukarıda karşılandığını; güçlü kapanış ise satışın tamamını kontrol edemediğini gösterir.', bullets: ['Açılış-kapanış gövdesi', 'Üst/alt fitil ve reddedilme', 'Kapanışın aralıktaki yeri', 'Zaman dilimi bağlamı'] }, { title: 'Formasyon değil bağlam', explanation: 'Pin bar veya engulfing adını bilmek yetmez. Formasyonun destek bölgesinde mi, dirençte mi, hacim artışıyla mı ve ana trend yönünde mi oluştuğunu kontrol et.', example: 'Destekte oluşan uzun alt fitilli mumun ertesi günü tepe kırılır ve hacim artarsa reddedilme teyit alır; tek mumla işlem açılmaz.', bullets: ['Destek/direnç konumu', 'Önceki trend', 'Hacim teyidi', 'Ertesi mum teyidi'] }, { title: 'Fiyat aksiyonundan plan üret', explanation: 'Giriş, stop ve hedefi mumun içine saklama. Mumun geçersiz olduğu fiyatı stop, alıcıların yeniden güç kazanmasını beklediğin bölgeyi giriş tetikleyicisi olarak yaz.', example: '50 TL destekteki bullish engulfing için 49.20 TL altı kapanış geçersiz, 52 TL üzeri hacimli kapanış teyit, 55 TL ilk hedef olabilir.', bullets: ['Tetikleyici', 'Geçersizlik', 'Hedef bölgesi', 'Pozisyon boyutu'] }], questions: [{ question: 'Uzun fitil her zaman dönüş mü demek?', answer: 'Hayır. Fitil yalnızca o fiyat bölgesinde reddedilme olduğunu gösterir. Trend, hacim ve sonraki kapanış teyidi olmadan dönüş varsayılmaz.' }, { question: 'Mum hangi zaman diliminde okunmalı?', answer: 'İşlem ufkunla aynı zaman dilimini ana referans yap; üst zaman dilimini yön, alt zaman dilimini giriş hassasiyeti için kullan.' }, { question: 'İki ters sinyal varsa?', answer: 'Önce üst zaman dilimi ve kritik seviye önceliklidir. Belirsizliği pozisyonu küçülterek veya işlem açmayarak yönet.' }] },
    'rsi-ve-macd': { lead: 'RSI momentumun hızını ve aşırılaşmasını, MACD ise iki hareketli ortalama arasındaki momentum farkını izler. İkisini trend yönü ve fiyat yapısından bağımsız kullanmak en yaygın hatadır.', sections: [{ title: 'RSI ne anlatır?', explanation: 'RSI 0-100 arasında dalgalanır. 70 üzeri otomatik SAT, 30 altı otomatik AL değildir; güçlü trendlerde RSI uzun süre aşırı bölgede kalabilir.', example: 'Yukarı trendde RSI 45-80 bandında çalışıyorsa 50 civarına geri çekilme trend içi soluklanma olabilir.', bullets: ['Aşırılaşma', 'Trend bandı', 'Uyumsuzluk', '50 seviyesi'] }, { title: 'MACD nasıl okunur?', explanation: 'MACD çizgisi ve sinyal çizgisi kesişiminden önce histogram momentumun hızlanıp yavaşladığını gösterir. Sıfır çizgisi fiyatın ortalamalara göre rejimini anlamaya yardım eder.', example: 'MACD yukarı kesişirken fiyat hâlâ SMA200 altında ise kısa vadeli toparlanma uzun vadeli trend dönüşü olmayabilir.', bullets: ['Kesişim', 'Histogram', 'Sıfır çizgisi', 'Gecikme'] }, { title: 'Uyumsuzluk ve teyit', explanation: 'Fiyat yeni tepe yaparken RSI/MACD daha düşük tepe yapıyorsa momentum zayıflıyor olabilir; bu tek başına dönüş değil dikkat sinyalidir.', example: 'Uyumsuzluk + direnç reddi + hacim düşüşü birlikte görülürse kademeli kâr alma planı güçlenir.', bullets: ['Fiyat-momentum farkı', 'Seviye teyidi', 'Hacim', 'Stop'] }], questions: [{ question: 'RSI 70 üstünde AL olur mu?', answer: 'Güçlü trendde olabilir; önemli olan RSI’ın hangi bantta kaldığı ve fiyatın dirençte mi yoksa yeni kırılımda mı olduğudur.' }, { question: 'MACD kesişimi neden geç kalır?', answer: 'Hareketli ortalamalara dayandığı için geçmiş fiyatı yumuşatır. Bu yüzden ilk girişten çok trend teyidi veya pozisyon yönetiminde kullanılır.' }] },
    'fibonacci-ve-trend-kanallari': { lead: 'Fibonacci geri çekilmesi bir fiyat kehaneti değil, belirgin bir hareketin hangi oranlarda soluklanabileceğini düzenleyen bir ölçüm aracıdır. Trend kanalı ise fiyatın yön ve oynaklık sınırlarını görselleştirir.', sections: [{ title: 'Doğru swing seçimi', explanation: 'Fibonacci’yi rastgele iki noktaya çekmek anlamsız seviyeler üretir. Belirgin bir dipten tepeye veya tepeden dibe, hacim ve zaman açısından anlamlı hareket seçilir.', example: '100’den 140’a yükselen dalgada 0.618 geri çekilmesi yaklaşık 115.28 TL’dir; bu fiyat tek başına alım emri değildir.', bullets: ['Belirgin dip/tepe', 'Ana trend', 'Hareketin hacmi', 'Zaman ufku'] }, { title: 'Kesişim bölgesi', explanation: 'Fib seviyesi, yatay destek, hareketli ortalama ve kanal sınırı aynı bölgede birleşiyorsa alanın önemi artar. Buna confluence denir.', example: '0.5 Fib seviyesi SMA50 ile kesişiyor ve önceki yatay destek aynı bölgede ise tepki ihtimali tek Fib çizgisinden daha anlamlıdır.', bullets: ['0.382 / 0.5 / 0.618', 'Kanal sınırı', 'Ortalama', 'Hacim'] }, { title: 'Kanal kırılımı', explanation: 'Kanal dışına fitil atılması kırılım değildir. Kapanış, hacim ve retest ile teyit aranır; stop kanalın içine veya yapının geçersiz olduğu noktaya konur.', example: 'Üst kanal kırıldıktan sonra fiyat kanala geri girerse breakout yerine yanlış kırılım senaryosu çalışabilir.', bullets: ['Kapanış', 'Hacim', 'Retest', 'Hedef uzatması'] }], questions: [{ question: 'Fib 0.618 kesin dönüş seviyesi mi?', answer: 'Hayır. Sadece izlenecek geri çekilme oranıdır. Fiyat davranışı ve diğer teyitler olmadan karar verilmez.' }, { question: 'Trend kanalı nasıl geçersiz olur?', answer: 'Ana trend yönünün tersinde güçlü kapanış, hacim ve retest ile kanal varsayımı geçersiz kabul edilir.' }] },
    'takas-analizi': { lead: 'Takas analizi, hissede hangi aracı kurumların ne kadar pozisyon taşıdığını ve maliyetin hangi bölgelerde yoğunlaştığını anlamaya çalışır. Kurum adı görmek tek başına alıcıyı veya geleceği garanti etmez.', sections: [{ title: 'Net alıcıyı doğru oku', explanation: 'Bir kurumun net alımı, kendi müşterilerinin toplam davranışıdır; kurumun kesinlikle kendi adına yatırım yaptığı anlamına gelmez. Değişimi birkaç gün, fiyat ve hacimle birlikte izle.', example: 'Beş gün boyunca net alım artarken fiyat yükselmiyorsa dağıtım, likidite emilimi veya karşı tarafta güçlü satış araştırılmalıdır.', bullets: ['Net değişim', 'Kurum yoğunluğu', 'Maliyet bölgesi', 'Fiyat-hacim'] }, { title: 'Maliyet bölgesi', explanation: 'Yoğunlaşan maliyet, fiyat o bölgeye geldiğinde destek veya zarar kesme kaynaklı arz üretebilir. Maliyet üstü/altı kapanış davranışı önemlidir.', example: 'Ana alıcı kurumların maliyeti 30 TL, fiyat 35 TL ise bu seviyenin artık destek gibi çalışıp çalışmadığı takip edilir; otomatik destek sayılmaz.', bullets: ['Maliyet üstü', 'Maliyet altı', 'Yoğunlaşma', 'Likidite'] }, { title: 'AKD ile birleştir', explanation: 'Gün içi AKD akışı ile dönemsel takas aynı hikâyeyi teyit ediyorsa sinyal güçlenir; çelişiyorsa pozisyon boyutu ve teyit süresi artırılır.', example: 'Gün içi alıcı görünen kurumun haftalık takasta sürekli satıcı olması kısa vadeli akışın kalıcı olmayabileceğini gösterir.', bullets: ['Gün içi akış', 'Haftalık takas', 'Kapanış davranışı', 'Teyit'] }], questions: [{ question: 'Takas verisi ne sıklıkta kullanılmalı?', answer: 'Takas daha yavaş pozisyonlanmayı, AKD daha kısa akışı anlatır. İşlem ufkuna göre gün, hafta ve ay bağlamını birlikte kullan.' }, { question: 'Bir kurum net alıcıysa hisse alınır mı?', answer: 'Hayır. Haber, değerleme, fiyat yapısı ve likidite kontrol edilmeden kurum akışı tek başına gerekçe değildir.' }] },
};

export function getEducationGuide(slug: string): EducationGuide {
    if (!slug) return GENERIC;
    if (GUIDES[slug]) return GUIDES[slug];
    const title = slug.split('-').join(' ');
    return {
        lead: `${title} konusunu tanım, ölçüm, uygulama ve risk yönetimi birlikte ele alarak çalış. Bu ders, kavramı ezberletmek yerine gerçek bir hisse üzerinde nasıl sınayacağını gösterir.`,
        sections: [
            { title: 'Kavramın temeli', explanation: `${title} neyi ölçer, hangi verilerden beslenir ve hangi zaman ufkunda anlamlıdır? Önce kavramın kapsamını belirle; tek başına alım-satım emri gibi kullanma.`, example: `Bir hisse seç, ${title} için kullanılan veriyi son 20-50 gözlem boyunca kaydet ve ölçümün hangi koşullarda değiştiğini not et.`, bullets: ['Tanım ve temel bileşenler', 'Kullanılan veri', 'Zaman ufku', 'Sık yapılan yanlış yorum'] },
            { title: 'Adım adım okuma', explanation: `Önce veriyi doğrula, sonra ${title} sinyalini trend, fiyat seviyesi, hacim ve haber akışıyla karşılaştır. Sinyalin oluştuğu bağlamı yazmadan sonuç çıkarma.`, example: `Aynı sinyali yükselen, yatay ve düşen üç farklı piyasada karşılaştır; her birinde giriş, teyit ve geçersizlik koşulunu ayrı yaz.`, bullets: ['Veriyi doğrula', 'Bağlamı kontrol et', 'Teyit ara', 'Geçersizlik seviyesi belirle'] },
            { title: 'Uygulama ve ölçüm', explanation: `Kavramı geçmiş örnekler üzerinde test ederken sonucu yalnızca kazançla değerlendirme. Kazanma oranı, ortalama kazanç, ortalama kayıp, işlem maliyeti ve maksimum düşüşü birlikte ölç.`, example: `En az 30 geçmiş örnekte kuralları değiştirmeden kayıt tut; sonucun tesadüf mü yoksa tekrar edilebilir bir avantaj mı olduğunu incele.`, bullets: ['Kural seti yaz', 'Örneklem oluştur', 'Maliyetleri ekle', 'Sonuçları karşılaştır'] },
            { title: 'Risk ve karar planı', explanation: `En iyi görünen senaryoda bile risk tanımlı değilse analiz tamamlanmış sayılmaz. Pozisyon boyutunu stop mesafesine göre ayarla ve haber şokunda planın nasıl değişeceğini önceden yaz.`, example: `İşlem başına portföyün %1’ini riske et; giriş-stop mesafesi büyüdükçe lotu azalt ve hedefe ulaşmadan önce hangi koşulda çıkacağını belirt.`, bullets: ['İşlem başı risk', 'Pozisyon boyutu', 'Hedef ve stop', 'Haber senaryosu'] },
        ],
        questions: [{ question: `${title} tek başına karar vermek için yeterli mi?`, answer: 'Hayır. Trend, likidite, haber, maliyet ve portföy riskiyle birlikte değerlendirilmelidir.' }, { question: 'Ne zaman yanıltıcı olabilir?', answer: 'Veri gecikmeli veya hatalı olduğunda, piyasa rejimi değiştiğinde, likidite düştüğünde ve haber şoku geldiğinde geçmiş ilişki bozulabilir.' }],
    };
}
